### ISSUE TITLE
Add customizable header text to application page

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#155]
While there is still a push to have a fully customized application, a nice first step is to add a text box to the top of the application page so that individual chapters can speak to their applicants on the application page to steer them in the right direction and make sure that they get good applications. 

~Blocked on #154 since this only really makes sense if the "select your chapter" link is at the top of the page.~

Requirements:
- Text area input on the chapter edit page
- Display the text on the application page
- Dynamically change that text if the applicant changes the chapter with the dropdown
- Ensure that the text is loaded properly when the page is first loaded

See attached screenshot for details.

![screen shot 2014-09-21 at 6 58 07 pm](https://cloud.githubusercontent.com/assets/2909/4350299/cef8cc16-41e2-11e4-9b53-25bdb05b3d56.png)

**Comment by avicaplan** [comment]
It might be more intuitive to have the custom text appear below the "Select chapter to apply to" drop-down. Otherwise, I think many users will not notice that new text has appeared at the top of the page. With new text appearing at the top of the page, the drop-down would also move down the page from under the mouse, which I think would be a bit weird.
