### ISSUE TITLE
Can't edit main project description fields

### ISSUE THREAD

**Issue by frabcus** [awesomefoundation/awesomebits#185]
As a Dean, I can edit the headline project fields, but strangely can't edit the main details:

e.g. "Tell us about your awesome project!"

We've a project we need to alter the description of before we can make the text public (as they've won), because they put something in that can't be public (yet).

Is there any particular reason why these fields aren't editable by Deans?

**Comment by jcn** [comment]
The main submission fields are intentionally frozen since this is the text directly from the applicant and we feel that it makes sense to ensure that their words are kept as they applied.

For the use case that you're talking about, we include a "funded description" field at the bottom of the form which can be edited as much as you would like and is the field that is displayed on the public project page. [More details can be found on the wiki](http://wiki.awesomestudies.org/index.php?title=Website_Manual#Selecting_a_Winner).

**Comment by frabcus** [comment]
Ah OK, I didn't spotted the box way below!

Something next to the uneditable boxes saying that would be useful!
