### ISSUE TITLE
Specify default image for page sharing on Facebook

### ISSUE THREAD

**Issue by avicaplan** [awesomefoundation/awesomebits#259]
When sharing a chapter page or the main awesomefoundation.org landing page on Facebook the images to choose from are the ones from recently winning projects. I believe it may be possible for us to specify a generic Awesome Foundation logo instead.

**Comment by jcn** [comment]
@avicaplan This is fixed (this used to work, but Facebook is now ignoring smaller images) and should start working for all sites eventually. Since Facebook caches those images though, if you want to clear it immediately, go to https://developers.facebook.com/tools/debug/sharing/ and enter the page you want to clear and you can have it refetch the image.

**Comment by avicaplan** [comment]
Looks great! Thanks for the speedy fix. :)
