### ISSUE TITLE
Hiding a project fails if it has an invalid URL

### ISSUE THREAD

**Issue by forensicgarlic** [awesomefoundation/awesomebits#290]
hiding has just been enabled for non-deans, so I'm working on using it for the Chicago chapter. I successfully hid this application http://www.awesomefoundation.org/en/chapters/chicago/projects/87565-maven-xchange because it's funding for a business -- an application that won't meet our awesome criteria. 
I then found these two duplicate applications: http://www.awesomefoundation.org/en/chapters/chicago/projects/87473-minority-rule-radio-station-owner-broadcaster-in and http://www.awesomefoundation.org/en/chapters/chicago/projects/87472-minority-rule-radio-station-owner-broadcaster-in . When I try to hide either of them, they hide doesn't appear to take.

**Comment by forensicgarlic** [comment]
subsequently, I was able to hide this project http://www.awesomefoundation.org/en/chapters/chicago/projects/86515-we-the-w-h-ee (travel and training for one person doesn't meet our awesome criteria).

**Comment by jcn** [comment]
@forensicgarlic Oh, I figured out the problem. Since I updated the system to not allow invalid websites, you have to update the project to have a "real" web address before hiding will work.

This won't be a problem moving forward since all projects will have a real web address, but for older projects, this is what's going on.

I'll try to come up with a better solution, but for right now, the (annoying) workaround is to remove the web address first, then try to hide the project. :(

**Comment by forensicgarlic** [comment]
sounds like it'll be a relatively short term problem too, so it's fine for it to be low / zero priority unless someone else notices it.

**Comment by zarino** [comment]
I just came across this while attempting to mark a project as Winner for our chapter this month. The project was submitted a few weeks ago, and had a URL of "http://none at present". 

Editing the project, removing the URL, and saving, then allowed me to mark the project as a Winner.

**Comment by jcn** [comment]
@zarino That makes sense, and I'm kind of glad you ran into that since having a broken URL would have been a terrible user experience for anyone visiting that page. 

Thanks everyone for testing this and reporting your issues - this is very helpful.
