### ISSUE TITLE
Improved experience of setting a funded project

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#379]

**Comment by avicaplan** [comment]
As part of this workflow, could we have a checkbox for something along the lines of "This is a particularly awesome project that should be considered for wider global publicity"? I think this would be helpful for the newsletter folks.

**Comment by nkkl** [comment]
My current thinking is that we add an interstitial page that `Winner for XX` takes you to, so that you can review and edit before publishing the grant. Once you've edited to your heart's content and published the grant, we'll take you back to your chapter dashboard, which mirrors today's workflow (e.g. setting a project as winner doesn't take you out of your dashboard).

V1 of the workflow:
![image](https://user-images.githubusercontent.com/766654/57586130-18bddd00-74a6-11e9-9766-1562fe817ab9.png)

Detailed interstitial page:
![image](https://user-images.githubusercontent.com/766654/57586060-e95aa080-74a4-11e9-86d0-123ff658c8cc.png)

https://www.figma.com/file/IDr59xwwehwaBJPzZ2W1g3eR/Set-winning-project-interstitial?node-id=0%3A1

**Comment by avicaplan** [comment]
Looks great! A few quick reactions from the peanut gallery:
- I'm not sure if the date is the thing I'd expect to see at the top (and the "out" can probably be dropped from the label)
- The name of the winner seems to be missing from the mock-up
- Maybe it would be worth mentioning in the label for the project description something along the lines of "Some chapters fill this out as if it were a news release about the winner" or some such.
- I think we can now drop the label "Images are automatically resized..." as they will be shown in different ways soon, and I'm not sure we are getting errors any more caused by too many or too large pictures(?)
- The button at the bottom might more closely match the language of the label at the top of the form (i.e., "Publish winning project"). Or, if we want the language to be more flexible for other giving circle networks, the language at the top could change instead (i.e., "Confirm grant details").

**Comment by nkkl** [comment]
I put the date at the top because it's the only thing that the dean is guaranteedly changing. Instead of litigating the design, let's test it with our users.

The winner name should definitely be in there, yes. I will update.

I'm hesitant to start debating the specifics of the copy when we don't have a content guide of any sort - I can see us going down a rabbit hole of spending hours tweaking sentences without a consistent reference point. Maybe we can recruit some of our content-savvy trustees to pick out a content guide for us to build off of and then spend a little bit of time establishing how we talk about grants, grant winners, and trustees.

The checkbox is net new functionality and therefore not in scope for this particular iteration. Is there a separate issue for the need?

**Comment by nkkl** [comment]
Now with 100% more grantee name.

![image](https://user-images.githubusercontent.com/766654/57589190-6867cd00-74d5-11e9-8cea-685da6a7a1fc.png)

**Comment by avicaplan** [comment]
On content guide, no strong feelings which way the language goes here, but was just suggesting that the purpose at the top of the form might match the action of the button one way or the other – don't really care if we're talking about a winning project or a grant, but maybe should be consistent?

No, don't think an issue has been opened for functionality to flag particularly awesome projects – could do that if this one is tightly limited in scope.

**Comment by nkkl** [comment]
Sure sure, that works fine. It's mostly the rest of the content changes that set off my "oh no we need a content style guide" senses.

![image](https://user-images.githubusercontent.com/766654/57593843-213c0500-74f2-11e9-8362-02a4cc70ade5.png)

Let's open another issue for flagging particularly awesome projects. In particular, it would be really helpful if you specifically talk about the end goal - there may be multiple ways to achieve it, and I want to make sure that we make the right tradeoffs. 🙂

**Comment by avicaplan** [comment]
Here you go! https://github.com/awesomefoundation/awesomebits/issues/386
