### ISSUE TITLE
Ensure the project scroller on the chapter page works on mobile

### ISSUE THREAD

**Issue by jcn** [awesomefoundation/awesomebits#99]
Right now it's very difficult to see multiple projects (on the chapter page) because the "next" and "previous" buttons are activated on hover, which doesn't work on mobile.

We can leave this as next and last buttons if, in the mobile view (or even in the regular view) the buttons are always there (though if we do that we should reposition the buttons in mobile because they're not centered quite right). 

The other option is to make it a scrollable ribbon that you can just drag with your finger, though I'm not sure if that is the right interface. I leave it to better UX minds.

**Comment by forensicgarlic** [comment]
scrollable ribbon seems fine to me, though it'd be good if there was an indication in interface that it was scrollable.

**Comment by spacemunkay** [comment]
*Issue*
Using a mobile device. Visit https://www.awesomefoundation.org/en/chapters/sf.  Note that the images are not scrollable like they are when visiting the page via a desktop.  This makes it impossible to see all of a chapters projects on mobile devices.

*Feature*
Using a mobile device, it is possible to scroll sideways through the images, and it's obvious that the images are scrollable.  This could be implemented in the ways listed above in the previous comments.

*Mockup*
(a really crappy one)  Red rectangles could be button hit areas (swiping would make more sense instead of buttons, provided there's a way to show that it's swipeable).  Note the scrollbar below the image, just a suggested way to show that the images are scrollable.  
<img width="510" alt="screen shot 2018-05-29 at 11 20 10 pm" src="https://user-images.githubusercontent.com/384389/40702786-fc0bed16-6397-11e8-8cbc-c7cec74a1dae.png">

**Comment by ilya-konanykhin** [comment]
1. The current approach is to replace the current slider with a more robust and mobile-friendly open-source solution. Can't tell which exactly, tests are WIP.

    Apart from the slider becoming mobile friendly, this also simplifies future maintenance.

2. The desktop design is OK so I plan to leave it as is. The mobile design is somewhat dictated by the plugin to be chosen, and obviously it should contain some indication of possible actions (swipe, tap), like small dots or thumbnails below the current slide. I'll attach some screenshots later.

3. What I strongly believe should be done on mobile, is changing the current two-slides layout to a one slide at a time. Otherwise the slide picture, so as it's texts, are too small, see the attached screenshot (compare paragraph font size to the slider text font sizes).

Please feel free to add comments or request some.

PS this also applies to #100 

<img width="370" alt="2018-06-26 17 26 18" src="https://user-images.githubusercontent.com/8665049/41908842-2f94c542-7967-11e8-98ba-468924274d6f.png">

**Comment by ilya-konanykhin** [comment]
Appreciate the comments!

> If we could make the chapter page more readable on mobile

This is also a plan, but not to be done in the scope of this issue.

**Comment by jcn** [comment]
> not to be done in the scope of this issue.

Understood.
